--create procedure [dbo].[ServiceToLead_Insert]
--	@Period int,
--	@Price decimal,
--	@Status int,
--	@LeadId int,
--	@ServiceId int,
--	@TransactionId int
--as
--begin
--	insert into dbo.[ServiceToLead]
--		([Period],
--	     [Price],
--	     [Status],
--		 [LeadId],
--		 [ServiceId],
--		 [TransactionId])
--	values
--		(@Period,
--		 @Price,
--		 @Status,
--		 @LeadId,
--		 @ServiceId,
--		 @TransactionId)
--	select scope_identity()
--end